<?php

namespace humhub\modules\schedule\widgets;

use humhub\modules\faculties\models\UniversityFaculties;
use Yii;
use humhub\modules\questionanswer\helpers\Url;
use humhub\widgets\BaseMenu;
use yii\base\InvalidCallException;

class ScheduleAboutWidget extends BaseMenu
{
    /**
     * @inheritdoc
     */
    public $template = "@humhub/widgets/views/tabMenu";

    public function init()
    {
        $this->addItem([
            'label' => 'Что такое расписание?',
            'icon' => '<i class="fa fa-bars"></i>',
            'url' => Url::to('/schedule/about'),
            'sortOrder' => 100,
            'isActive' => (Yii::$app->controller->module && Yii::$app->controller->module->id == 'schedule' && Yii::$app->controller->id == 'about'),
        ]);

        return parent::init(); // TODO: Change the autogenerated stub
    }
}